name: Validate

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'
      - name: Run Lint
        run: ./gradlew lintDebug --no-daemon
      - name: Zip reports
        if: always()
        run: zip -r reports.zip . -i '**/reports/*.xml' '**/reports/*.html'
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: lint_reports
          path: reports.zip
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --no-daemon
      - name: Zip reports
        if: always()
        run: zip -r reports.zip . -i '**/reports/*.xml' '**/reports/*.html'
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_reports
          path: reports.zip